
# Basic parameters
CC     = gcc 
CFLAGS = -Wall -Wextra 
OBJS   = main.o BinaryTrees.o
DEPS   = BinaryTrees.h

#------------------------------------------------------------
#  make       : to compile the code. 
#  make run   : to compile and execute the code.
#  make clean : remove all files generated by "make" 
#------------------------------------------------------------

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

main: $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

all:
	make main
	
run: all
	./main

clean:
	/bin/rm -rf *.o *~
	/bin/rm -rf main
